### ISSUE TITLE
Consider dateutil parser?

### ISSUE THREAD

**Issue by bdillahu** [click-contrib/click-datetime#4]
Just as a thought/suggestion... maybe consider using python-dateutil parser so that, instead of having to define a format, it can "guess" one... I've found it to be pretty accurate.

https://dateutil.readthedocs.io/en/stable/parser.html

Thanks for this regardless... was already a big timesaver!

**Comment by liiight** [comment]
+1 for this. Dateutil is much more versatile than standard datetime. 
Thank you for this!

**Comment by EpicWink** [comment]
Or, for absolutely over-the-top date/time parsing: https://dateparser.readthedocs.io/en/latest/. This provides a best-guess without having to specify a format ahead of time

Might want to add as an extra requirement though (eg `pip install click-datetime[parser]`)

**Comment by ddaws** [comment]
I am going to close this because I don't want to add more dependencies to this package. I think this should be a new package, like `click-dateutil` or `click-dateparser`.
