### ISSUE TITLE
Make new release with README fix

### ISSUE THREAD

**Issue by leohemsted** [click-contrib/click-datetime#7]
Fix was merged here: https://github.com/assiotis/click-datetime/pull/1

Without this I can't build this from source, which I would like due to other packages i'm installing at the same time requiring pip `--global-options`, which disable use of wheels.

Is it possible to make a new patch version of click-datetime and release it to pypi?

**Comment by yegorich** [comment]
Any update on this issue?

**Comment by ddaws** [comment]
Published a new 0.3.0 version that should fix this
